### PR TITLE
[DRAFT] 3.0.0

### PR DESCRIPTION
**Pull request by fuccsoc**

### CODE REVIEW

**Comment by fuccsoc** [comment]
**Changelog:**
- Rewrite imports to catch possible errors while startup
- Some info message reformatted
- Move utils to root dir
- ...

**Comment by A9FM** [comment]
хуйня

**Comment by iamnalinor** [comment]
@A9FM какие люди у нас тут

**Comment by fuccsoc** [comment]
Closed due to author issue

**Pull request closed without merging**
