### PR TITLE
Update squotes module

### PR DESCRIPTION
**Pull request by iamnalinor**
New command .getpng, which resends sticker in PNG-file

New argument !noreply: make a quote without showing a reply (for several messages, the first message won't get reply)

Added caching for downloading media (less floodwaits and more speed)

### CODE REVIEW

**Comment by fuccsoc** [comment]
@iamnalinor getpng лучше как флаг .q
if 'file' in message.message.split():
        # Send file

**Comment by ahmedov777-ai** [comment]
@iamnalinor -_-

**Comment by fuccsoc** [comment]
Changes:
- Help syntax updated
- .getpng removed (as it already exist)

Please, wirte a help note for `!noreply` argument and I'll merge it. Thanks.

**Comment by iamnalinor** [comment]
> Please, wirte a help note for `!noreply` argument and I'll merge it. Thanks.

Done. @fuccsoc

**Pull request merged**
