### PR TITLE
update neko.py

### PR DESCRIPTION
**Pull request by NavernoeDa**
**Difference from the default version:**

- Add try:except:
- Before: a request is made -> a message is deleted -> the result appears in a new message
- Now: a request is made -> he message is being edited -> the result is displayed in the same message

### CODE REVIEW

**Comment by fuccsoc** [comment]
@NavernoeDa нhe, отвечаю

**Comment by john-phonk** [comment]
what is the reason for deletion neko_spam?

**Comment by NavernoeDa** [comment]
> 
> 
> what is the reason for deletion neko_spam?

i found it unnecessary. should i return it?

**Comment by john-phonk** [comment]
yea

**Pull request merged**
