### PR TITLE
[DRAFT] 3.0.0

### PR DESCRIPTION
**Pull request by iamnalinor**
**Changelog:**
- Rewrite imports to catch possible errors while startup
- Most of messages reformatted to bold
- Move utils to root dir
- SQLite DB type implemented
- Fixed some errors like "database is locked"
- Admintool bug fixes and improvements
- New modules: stickers, url

Developers: @iamnalinor, @fuccsoc

### CODE REVIEW

**Comment by john-phonk** [comment]
@iamnalinor

**Comment by john-phonk** [comment]
@john-phonk Бля

**Comment by john-phonk** [comment]
ну че пацаны, 3.0

**Comment by ahmedov777-ai** [comment]
@john-phonk Ипать,Ахуеее

**Pull request merged**
